"""Infrastructure taxonomy — 80+ component types across 12 layers.

Each component type defines:
  - layer: which of the 12 infrastructure layers it belongs to
  - keywords: code/identifier keywords that signal this component (10-20 each)
  - file_patterns: filename globs where this component is typically implemented
  - config_patterns: environment variable prefixes or config keys that signal this component

This taxonomy was compiled from analysis of 50+ open-source projects
across web apps, APIs, microservices, and data platforms.
"""

from __future__ import annotations

from typing import Final, TypedDict

# ---------------------------------------------------------------------------
# The 12 Infrastructure Layers
# ---------------------------------------------------------------------------

INFRASTRUCTURE_LAYERS: Final[tuple[str, ...]] = (
    "identity",
    "transaction",
    "state",
    "data",
    "communication",
    "delivery",
    "observability",
    "security",
    "deployment",
    "integration",
    "user_experience",
    "governance",
)


# ---------------------------------------------------------------------------
# Component Type Definitions (80+ types across 12 layers)
# ---------------------------------------------------------------------------


class TaxonomyEntry(TypedDict):
    """One infrastructure component type: its layer and detection signals."""

    layer: str
    keywords: tuple[str, ...]
    file_patterns: tuple[str, ...]
    config_patterns: tuple[str, ...]


INFRASTRUCTURE_TAXONOMY: Final[dict[str, TaxonomyEntry]] = {
    # ===================================================================
    # LAYER 1: IDENTITY — Authentication, Authorization, Access Control
    # ===================================================================
    "authentication": {
        "layer": "identity",
        "keywords": (
            "login",
            "signin",
            "sign_in",
            "authenticate",
            "auth",
            "jwt",
            "token",
            "password",
            "credential",
            "passport",
            "session",
            "cookie",
            "bearer",
            "oauth",
            "oidc",
            "openid",
            "sso",
            "saml",
            "ldap",
            "active_directory",
            "mfa",
            "2fa",
            "totp",
            "webauthn",
            "fido",
            "passwordless",
            "magic_link",
            "refresh_token",
            "access_token",
            "id_token",
            "logout",
            "signout",
        ),
        "file_patterns": (
            "auth*",
            "login*",
            "signin*",
            "jwt*",
            "token*",
            "session*",
            "oauth*",
            "sso*",
            "saml*",
            "mfa*",
            "password*",
        ),
        "config_patterns": (
            "AUTH_",
            "JWT_",
            "SESSION_",
            "OAUTH_",
            "SSO_",
            "SAML_",
            "MFA_",
        ),
    },
    "authorization": {
        "layer": "identity",
        "keywords": (
            "authorize",
            "authorization",
            "rbac",
            "acl",
            "permission",
            "role",
            "policy",
            "scope",
            "claim",
            "entitlement",
            "access_control",
            "casbin",
            "opa",
            "cedar",
            "zanzibar",
            "scope",
            "resource",
            "action",
        ),
        "file_patterns": (
            "authorize*",
            "rbac*",
            "permission*",
            "role*",
            "policy*",
            "acl*",
        ),
        "config_patterns": ("RBAC_", "PERMISSION_", "ROLE_", "POLICY_", "OPA_"),
    },
    "api_key_management": {
        "layer": "identity",
        "keywords": (
            "api_key",
            "apikey",
            "api_secret",
            "client_id",
            "client_secret",
            "consumer_key",
            "consumer_secret",
            "access_key",
            "secret_key",
            "hmac",
            "signature",
            "hmac_sha256",
            "api_gateway_key",
        ),
        "file_patterns": ("apikey*", "api_key*", "client*", "hmac*", "signature*"),
        "config_patterns": (
            "API_KEY",
            "API_SECRET",
            "CLIENT_ID",
            "CLIENT_SECRET",
            "HMAC_",
        ),
    },
    "user_management": {
        "layer": "identity",
        "keywords": (
            "register",
            "registration",
            "signup",
            "sign_up",
            "user",
            "profile",
            "account",
            "email_verification",
            "email_confirmation",
            "password_reset",
            "forgot_password",
            "change_password",
            "delete_account",
            "deactivate",
        ),
        "file_patterns": (
            "register*",
            "signup*",
            "user*",
            "profile*",
            "account*",
            "password*",
        ),
        "config_patterns": ("USER_", "REGISTRATION_", "EMAIL_VERIFICATION_"),
    },
    # ===================================================================
    # LAYER 2: TRANSACTION — Payments, Billing, Subscriptions
    # ===================================================================
    "payment_gateway": {
        "layer": "transaction",
        "keywords": (
            "stripe",
            "paypal",
            "braintree",
            "adyen",
            "razorpay",
            "square",
            "checkout",
            "payment",
            "charge",
            "transaction",
            "refund",
            "capture",
            "authorize",
            "void",
            "webhook",
            "payment_intent",
            "payment_method",
            "card",
            "bank_transfer",
            "ach",
            "sepa",
            "boleto",
            "alipay",
            "wechat_pay",
            "apple_pay",
            "google_pay",
            "klarna",
            "affirm",
            "afterpay",
            "mercadopago",
            "mollie",
            "paystack",
            "flutterwave",
        ),
        "file_patterns": (
            "payment*",
            "checkout*",
            "billing*",
            "stripe*",
            "paypal*",
            "transaction*",
            "webhook*",
            "refund*",
        ),
        "config_patterns": (
            "STRIPE_",
            "PAYPAL_",
            "BRAINTREE_",
            "ADYEN_",
            "RAZORPAY_",
            "SQUARE_",
            "PAYMENT_",
            "CHECKOUT_",
        ),
    },
    "subscription_billing": {
        "layer": "transaction",
        "keywords": (
            "subscription",
            "plan",
            "recurring",
            "billing_cycle",
            "interval",
            "trial",
            "grace_period",
            "proration",
            "upgrade",
            "downgrade",
            "cancel",
            "pause",
            "resume",
            "metered",
            "usage_based",
            "tier",
            "quantity",
            "anchor",
            "billing_anchor",
        ),
        "file_patterns": (
            "subscription*",
            "plan*",
            "billing*",
            "recurring*",
            "tier*",
        ),
        "config_patterns": ("SUBSCRIPTION_", "BILLING_", "PLAN_", "TRIAL_"),
    },
    "invoicing": {
        "layer": "transaction",
        "keywords": (
            "invoice",
            "invoice_number",
            "line_item",
            "tax",
            "vat",
            "gst",
            "discount",
            "coupon",
            "promo_code",
            "credit_note",
            "debit_note",
            "pdf",
            "send_invoice",
            "due_date",
            "payment_terms",
        ),
        "file_patterns": ("invoice*", "tax*", "coupon*", "discount*", "credit*"),
        "config_patterns": ("INVOICE_", "TAX_", "COUPON_", "DISCOUNT_"),
    },
    # ===================================================================
    # LAYER 3: STATE — Caching, Sessions, Distributed Locks, Feature Flags
    # ===================================================================
    "cache_layer": {
        "layer": "state",
        "keywords": (
            "redis",
            "memcached",
            "cache",
            "caching",
            "ttl",
            "eviction",
            "lru",
            "lfu",
            "write_through",
            "write_back",
            "cache_aside",
            "invalidation",
            "cache_key",
            "cache_tag",
            "warming",
            "hydration",
            "cache_control",
            "etag",
            "last_modified",
            "stale_while_revalidate",
        ),
        "file_patterns": (
            "cache*",
            "redis*",
            "memcached*",
            "ttl*",
            "invalidation*",
        ),
        "config_patterns": ("REDIS_", "MEMCACHED_", "CACHE_", "TTL_"),
    },
    "session_store": {
        "layer": "state",
        "keywords": (
            "session",
            "session_id",
            "session_data",
            "session_store",
            "cookie",
            "secure_cookie",
            "httponly",
            "same_site",
            "csrf",
            "xsrf",
            "session_regeneration",
            "session_fixation",
            "sliding_expiry",
        ),
        "file_patterns": ("session*", "cookie*", "csrf*", "xsrf*"),
        "config_patterns": ("SESSION_", "COOKIE_", "CSRF_", "XSRF_"),
    },
    "distributed_lock": {
        "layer": "state",
        "keywords": (
            "lock",
            "mutex",
            "semaphore",
            "distributed_lock",
            "redlock",
            "redisson",
            "etcd_lock",
            "consul_lock",
            "zookeeper_lock",
            "acquire",
            "release",
            "lease",
            "fencing",
            "token",
        ),
        "file_patterns": ("lock*", "mutex*", "semaphore*", "redlock*"),
        "config_patterns": ("LOCK_", "MUTEX_", "LEASE_"),
    },
    "feature_flag": {
        "layer": "state",
        "keywords": (
            "feature_flag",
            "feature_toggle",
            "fflag",
            "launchdarkly",
            "split",
            "unleash",
            "flagsmith",
            "configcat",
            "rollout",
            "percentage",
            "targeting",
            "segment",
            "experiment",
            "variant",
            "control",
            "treatment",
            "kill_switch",
            "dark_launch",
        ),
        "file_patterns": ("feature*", "flag*", "toggle*", "rollout*", "experiment*"),
        "config_patterns": (
            "FEATURE_",
            "FLAG_",
            "ROLLOUT_",
            "EXPERIMENT_",
            "LD_",
            "SPLIT_",
        ),
    },
    # ===================================================================
    # LAYER 4: DATA — Databases, Search, Object Storage, ETL, Backups
    # ===================================================================
    "relational_database": {
        "layer": "data",
        "keywords": (
            "postgresql",
            "postgres",
            "mysql",
            "mariadb",
            "sqlite",
            "oracle",
            "sql_server",
            "sqlserver",
            "aurora",
            "rds",
            "cloudsql",
            "cockroachdb",
            "timescaledb",
            "crdb",
            "ysql",
            "ycql",
            "pg",
            "pgsql",
            "primary_key",
            "foreign_key",
            "index",
            "migration",
            "schema",
            "orm",
            "sqlalchemy",
            "django_orm",
            "prisma",
            "diesel",
            "gorm",
            "entity_framework",
            "hibernate",
            "jpa",
            "sequelize",
            "knex",
        ),
        "file_patterns": (
            "model*",
            "entity*",
            "schema*",
            "migration*",
            "repository*",
            "database*",
            "orm*",
            "pg*",
            "mysql*",
        ),
        "config_patterns": (
            "DATABASE_",
            "DB_",
            "POSTGRES_",
            "MYSQL_",
            "PG_",
            "SQLALCHEMY_",
            "PRISMA_",
            "DIESEL_",
        ),
    },
    "document_database": {
        "layer": "data",
        "keywords": (
            "mongodb",
            "mongo",
            "cosmosdb",
            "documentdb",
            "firestore",
            "dynamodb",
            "couchdb",
            "couchbase",
            "raven",
            "redis_json",
            "collection",
            "document",
            "bson",
            "objectid",
            "aggregation",
        ),
        "file_patterns": ("mongo*", "document*", "nosql*"),
        "config_patterns": ("MONGO_", "COSMOS_", "FIRESTORE_", "DYNAMODB_"),
    },
    "search_engine": {
        "layer": "data",
        "keywords": (
            "elasticsearch",
            "elastic",
            "opensearch",
            "solr",
            "algolia",
            "meilisearch",
            "typesense",
            "sonic",
            "quickwit",
            "bleve",
            "search",
            "index",
            "analyzer",
            "tokenizer",
            "stemmer",
            "fuzzy",
            "autocomplete",
            "suggestion",
            "highlight",
            "facets",
            "aggregation",
            "ranking",
            "relevance",
            "bm25",
            "tfidf",
        ),
        "file_patterns": (
            "search*",
            "elastic*",
            "opensearch*",
            "algolia*",
            "meilisearch*",
        ),
        "config_patterns": (
            "ELASTIC_",
            "OPENSEARCH_",
            "ALGOLIA_",
            "MEILISEARCH_",
            "SEARCH_",
        ),
    },
    "object_storage": {
        "layer": "data",
        "keywords": (
            "s3",
            "minio",
            "gcs",
            "google_cloud_storage",
            "azure_blob",
            "wasabi",
            "backblaze",
            "b2",
            "digitalocean_spaces",
            "linode_object",
            "bucket",
            "object",
            "multipart",
            "presigned",
            "signed_url",
            "cdn",
            "cdn_url",
            "cloudfront",
            "cloudflare_r2",
        ),
        "file_patterns": ("storage*", "s3*", "bucket*", "upload*", "download*"),
        "config_patterns": (
            "S3_",
            "MINIO_",
            "GCS_",
            "AZURE_BLOB_",
            "B2_",
            "R2_",
            "SPACES_",
        ),
    },
    "etl_pipeline": {
        "layer": "data",
        "keywords": (
            "etl",
            "elt",
            "airflow",
            "dagster",
            "prefect",
            "luigi",
            "temporal",
            "dbt",
            "fivetran",
            "stitch",
            "airbyte",
            "singer",
            "pipeline",
            "dag",
            "task",
            "operator",
            "sensor",
            "trigger",
            "schedule",
            "cron",
            "interval",
            "dependency",
            "xcom",
            "extract",
            "transform",
            "load",
            "incremental",
            "full_refresh",
        ),
        "file_patterns": ("dag*", "pipeline*", "etl*", "task*", "airflow*", "dbt*"),
        "config_patterns": ("AIRFLOW_", "DAGSTER_", "PREFECT_", "DBT_", "TEMPORAL_"),
    },
    "data_warehouse": {
        "layer": "data",
        "keywords": (
            "snowflake",
            "bigquery",
            "redshift",
            "clickhouse",
            "databricks",
            "synapse",
            "athena",
            "trino",
            "presto",
            "druid",
            "pinot",
            "columnar",
            "olap",
            "fact_table",
            "dimension",
            "star_schema",
            "snowflake_schema",
            "materialized_view",
        ),
        "file_patterns": ("warehouse*", "analytics*", "olap*", "dw*"),
        "config_patterns": ("SNOWFLAKE_", "BIGQUERY_", "REDSHIFT_", "CLICKHOUSE_"),
    },
    "backup_restore": {
        "layer": "data",
        "keywords": (
            "backup",
            "restore",
            "snapshot",
            "point_in_time_recovery",
            "pitr",
            "pg_dump",
            "mysqldump",
            "mongodump",
            "wal_g",
            "barman",
            "replication",
            "replica",
            "standby",
            "failover",
            "switchover",
            "rpo",
            "rto",
            "retention",
            "archive",
            "cold_storage",
        ),
        "file_patterns": ("backup*", "restore*", "snapshot*", "replica*", "wal*"),
        "config_patterns": ("BACKUP_", "RESTORE_", "SNAPSHOT_", "REPLICATION_"),
    },
    # ===================================================================
    # LAYER 5: COMMUNICATION — REST, GraphQL, gRPC, WebSocket, Queues, Events
    # ===================================================================
    "rest_api": {
        "layer": "communication",
        "keywords": (
            "rest",
            "restful",
            "http",
            "get",
            "post",
            "put",
            "patch",
            "delete",
            "endpoint",
            "route",
            "resource",
            "controller",
            "handler",
            "middleware",
            "request",
            "response",
            "status_code",
            "header",
            "query_param",
            "path_param",
            "body",
            "json",
            "xml",
            "form_data",
            "openapi",
            "swagger",
            "api_spec",
            "schema",
        ),
        "file_patterns": (
            "api*",
            "route*",
            "controller*",
            "handler*",
            "endpoint*",
            "rest*",
        ),
        "config_patterns": ("API_", "HTTP_", "REST_"),
    },
    "graphql_api": {
        "layer": "communication",
        "keywords": (
            "graphql",
            "query",
            "mutation",
            "subscription",
            "schema",
            "resolver",
            "type",
            "field",
            "argument",
            "directive",
            "apollo",
            "graphene",
            "strawberry",
            "ariadne",
            "gql",
            "n_plus_one",
            "dataloader",
            "batching",
            "complexity",
            "depth_limit",
            "introspection",
            "playground",
            "voyager",
        ),
        "file_patterns": ("graphql*", "gql*", "schema*", "resolver*", "mutation*"),
        "config_patterns": ("GRAPHQL_", "APOLLO_", "GQL_"),
    },
    "grpc_service": {
        "layer": "communication",
        "keywords": (
            "grpc",
            "protobuf",
            "proto",
            "service",
            "rpc",
            "unary",
            "streaming",
            "client_streaming",
            "server_streaming",
            "bidirectional",
            "deadline",
            "cancellation",
            "interceptor",
            "reflection",
            "health_check",
            "load_balancing",
            "retry",
            "timeout",
            "compression",
            "proto3",
            "grpc_gateway",
        ),
        "file_patterns": ("grpc*", "proto*", "protobuf*", "service*", "rpc*"),
        "config_patterns": ("GRPC_", "PROTO_", "PROTOBUF_"),
    },
    "websocket": {
        "layer": "communication",
        "keywords": (
            "websocket",
            "ws",
            "wss",
            "socket.io",
            "socketio",
            "pusher",
            "ably",
            "centrifugo",
            "gorilla",
            "ws",
            "connection",
            "message",
            "broadcast",
            "room",
            "channel",
            "presence",
            "heartbeat",
            "ping",
            "pong",
            "reconnect",
            "fallback",
        ),
        "file_patterns": ("websocket*", "ws*", "socket*", "realtime*"),
        "config_patterns": ("WS_", "WEBSOCKET_", "SOCKETIO_", "PUSHER_"),
    },
    "message_queue": {
        "layer": "communication",
        "keywords": (
            "rabbitmq",
            "rabbit",
            "amqp",
            "queue",
            "exchange",
            "binding",
            "routing_key",
            "dead_letter",
            "dlx",
            "ttl",
            "priority",
            "kafka",
            "topic",
            "partition",
            "consumer_group",
            "offset",
            "consumer",
            "producer",
            "broker",
            "zookeeper",
            "kraft",
            "nats",
            "jetstream",
            "subject",
            "stream",
            "consumer",
            "redis_queue",
            "redis_stream",
            "list",
            "pubsub",
            "pub_sub",
            "sqs",
            "sns",
            "pubsub",
            "google_cloud_pubsub",
            "azure_service_bus",
        ),
        "file_patterns": (
            "queue*",
            "rabbit*",
            "kafka*",
            "nats*",
            "pubsub*",
            "sqs*",
            "consumer*",
            "producer*",
            "event*",
        ),
        "config_patterns": (
            "RABBITMQ_",
            "KAFKA_",
            "NATS_",
            "SQS_",
            "SNS_",
            "PUBSUB_",
            "RABBIT_",
            "KAFKA_",
            "NATS_",
        ),
    },
    "event_streaming": {
        "layer": "communication",
        "keywords": (
            "event",
            "event_driven",
            "event_sourcing",
            "cqrs",
            "command",
            "event_store",
            "event_bus",
            "domain_event",
            "integration_event",
            "outbox",
            "transactional_outbox",
            "cdc",
            "change_data_capture",
            "debezium",
            "kafka_connect",
            "schema_registry",
            "avro",
            "protobuf",
            "json_schema",
            "compatibility",
        ),
        "file_patterns": ("event*", "cdc*", "outbox*", "debezium*", "schema*"),
        "config_patterns": (
            "EVENT_",
            "CDC_",
            "OUTBOX_",
            "DEBEZIUM_",
            "SCHEMA_REGISTRY_",
        ),
    },
    # ===================================================================
    # LAYER 6: DELIVERY — CDN, Load Balancer, Reverse Proxy, API Gateway
    # ===================================================================
    "cdn": {
        "layer": "delivery",
        "keywords": (
            "cdn",
            "cloudflare",
            "cloudfront",
            "akamai",
            "fastly",
            "vercel",
            "netlify",
            "keycdn",
            "stackpath",
            "bunny",
            "azure_cdn",
            "google_cloud_cdn",
            "bunnycdn",
            "edge",
            "edge_network",
            "cache",
            "purge",
            "invalidate",
            "origin",
            "edge_node",
        ),
        "file_patterns": ("cdn*", "cloudflare*", "cloudfront*", "edge*"),
        "config_patterns": ("CDN_", "CLOUDFLARE_", "CLOUDFRONT_", "FASTLY_", "AKAMAI_"),
    },
    "load_balancer": {
        "layer": "delivery",
        "keywords": (
            "load_balancer",
            "lb",
            "nginx",
            "haproxy",
            "traefik",
            "envoy",
            "aws_alb",
            "aws_nlb",
            "aws_clb",
            "gcp_lb",
            "azure_lb",
            "round_robin",
            "least_connections",
            "ip_hash",
            "least_requests",
            "health_check",
            "upstream",
            "backend",
            "server",
            "weight",
            "sticky_session",
            "session_affinity",
        ),
        "file_patterns": (
            "nginx*",
            "haproxy*",
            "traefik*",
            "envoy*",
            "lb*",
            "loadbalancer*",
        ),
        "config_patterns": ("NGINX_", "HAPROXY_", "TRAEFIK_", "ENVOY_", "ALB_", "NLB_"),
    },
    "reverse_proxy": {
        "layer": "delivery",
        "keywords": (
            "reverse_proxy",
            "proxy_pass",
            "proxy_set_header",
            "x_forwarded",
            "x_real_ip",
            "host",
            "upgrade",
            "connection",
            "buffering",
            "caddy",
            "caddyfile",
            "openresty",
            "kong",
            "apisix",
            "traefik",
            "traefik_ingress",
            "ingress",
            "ingress_controller",
        ),
        "file_patterns": ("proxy*", "caddy*", "kong*", "apisix*", "openresty*"),
        "config_patterns": ("PROXY_", "CADDY_", "KONG_", "APISIX_", "OPENRESTY_"),
    },
    "api_gateway": {
        "layer": "delivery",
        "keywords": (
            "api_gateway",
            "gateway",
            "kong",
            "apisix",
            "traefik",
            "envoy",
            "aws_apigateway",
            "azure_apim",
            "gcp_apigateway",
            "tyk",
            "express_gateway",
            "krakend",
            "gravitee",
            "ambassador",
            "istio",
            "linkerd",
            "consul_connect",
            "service_mesh",
            "rate_limit",
            "quota",
            "auth",
            "jwt_validation",
            "transform",
        ),
        "file_patterns": (
            "gateway*",
            "kong*",
            "apisix*",
            "ambassador*",
            "istio*",
            "mesh*",
        ),
        "config_patterns": ("GATEWAY_", "KONG_", "APISIX_", "AMBASSADOR_", "ISTIO_"),
    },
    # ===================================================================
    # LAYER 7: OBSERVABILITY — Logging, Metrics, Tracing, Error Tracking
    # ===================================================================
    "logging": {
        "layer": "observability",
        "keywords": (
            "log",
            "logger",
            "logging",
            "log_level",
            "debug",
            "info",
            "warn",
            "error",
            "critical",
            "fatal",
            "trace",
            "structured_logging",
            "json_log",
            "logfmt",
            "loguru",
            "structlog",
            "zap",
            "zaplogger",
            "winston",
            "bunyan",
            "pino",
            "logrus",
            "zerolog",
            "slog",
            "context",
            "correlation_id",
            "request_id",
            "span_id",
            "trace_id",
            "sampling",
            "tail_sampling",
            "head_sampling",
        ),
        "file_patterns": (
            "log*",
            "logger*",
            "loguru*",
            "structlog*",
            "zap*",
            "winston*",
        ),
        "config_patterns": ("LOG_", "LOGGER_", "LOG_LEVEL_", "LOGURU_", "STRUCTLOG_"),
    },
    "metrics": {
        "layer": "observability",
        "keywords": (
            "metric",
            "metrics",
            "prometheus",
            "grafana",
            "datadog",
            "newrelic",
            "counter",
            "gauge",
            "histogram",
            "summary",
            "bucket",
            "label",
            "time_series",
            "scrape",
            "pushgateway",
            "alertmanager",
            "rule",
            "recording_rule",
            "alerting_rule",
            "expression",
            "query",
            "datadog_agent",
            "statsd",
            "statsd_exporter",
            "node_exporter",
            "cadvisor",
            "kube_state_metrics",
            "blackbox_exporter",
        ),
        "file_patterns": ("metric*", "prometheus*", "grafana*", "datadog*", "alert*"),
        "config_patterns": (
            "PROMETHEUS_",
            "GRAFANA_",
            "DATADOG_",
            "NEWRELIC_",
            "METRICS_",
        ),
    },
    "distributed_tracing": {
        "layer": "observability",
        "keywords": (
            "trace",
            "tracing",
            "distributed_tracing",
            "opentelemetry",
            "otel",
            "jaeger",
            "zipkin",
            "tempo",
            "sky_walking",
            "aws_xray",
            "span",
            "trace_id",
            "span_id",
            "parent_id",
            "baggage",
            "context_propagation",
            "w3c_tracecontext",
            "b3",
            "baggage",
            "exporter",
            "collector",
            "sampler",
            "always_on",
            "always_off",
            "probabilistic",
            "rate_limiting",
            "tail_sampling",
            "span_processor",
            "batch_processor",
            "simple_processor",
        ),
        "file_patterns": (
            "trace*",
            "otel*",
            "opentelemetry*",
            "jaeger*",
            "zipkin*",
            "tempo*",
        ),
        "config_patterns": (
            "OTEL_",
            "JAEGER_",
            "ZIPKIN_",
            "TEMPO_",
            "XRAY_",
            "TRACING_",
        ),
    },
    "error_tracking": {
        "layer": "observability",
        "keywords": (
            "sentry",
            "rollbar",
            "bugsnag",
            "airbrake",
            "honeybadger",
            "exception",
            "error",
            "crash",
            "stack_trace",
            "breadcrumbs",
            "release",
            "environment",
            "user_context",
            "tags",
            "fingerprint",
            "grouping",
            "alert",
            "notification",
            "webhook",
            "pagerduty",
            "opsgenie",
            "victorops",
            "slack",
            "email",
            "sms",
        ),
        "file_patterns": (
            "sentry*",
            "rollbar*",
            "bugsnag*",
            "airbrake*",
            "honeybadger*",
        ),
        "config_patterns": (
            "SENTRY_",
            "ROLLBAR_",
            "BUGSNAG_",
            "AIRBRAKE_",
            "HONEYBADGER_",
        ),
    },
    # ===================================================================
    # LAYER 8: SECURITY — Encryption, WAF, Secrets, Audit, Compliance
    # ===================================================================
    "encryption": {
        "layer": "security",
        "keywords": (
            "encrypt",
            "decrypt",
            "aes",
            "rsa",
            "ecdsa",
            "ed25519",
            "chacha20",
            "poly1305",
            "gcm",
            "aead",
            "fernet",
            "nacl",
            "libsodium",
            "bcrypt",
            "scrypt",
            "argon2",
            "pbkdf2",
            "hash",
            "hmac",
            "sha256",
            "sha512",
            "blake2",
            "blake3",
            "tls",
            "ssl",
            "certificate",
            "cert",
            "key",
            "pem",
            "der",
            "p12",
            "pfx",
            "jwk",
            "jws",
            "jwe",
            "jwa",
            "jwk_set",
        ),
        "file_patterns": (
            "crypto*",
            "encrypt*",
            "decrypt*",
            "tls*",
            "ssl*",
            "cert*",
            "key*",
        ),
        "config_patterns": (
            "ENCRYPT_",
            "TLS_",
            "SSL_",
            "CERT_",
            "KEY_",
            "JWT_",
            "JWK_",
        ),
    },
    "waf": {
        "layer": "security",
        "keywords": (
            "waf",
            "web_application_firewall",
            "cloudflare_waf",
            "aws_waf",
            "modsecurity",
            "coraza",
            "ngx_waf",
            "owasp",
            "crs",
            "core_rule_set",
            "sql_injection",
            "xss",
            "rfi",
            "lfi",
            "command_injection",
            "path_traversal",
            "xxe",
            "ssrf",
            "bot",
            "scanner",
            "crawler",
            "rate_limit",
            "ip_reputation",
            "geo_blocking",
            "challenge",
        ),
        "file_patterns": ("waf*", "modsecurity*", "security*", "owasp*"),
        "config_patterns": ("WAF_", "MODSECURITY_", "OWASP_", "CRS_"),
    },
    "secrets_management": {
        "layer": "security",
        "keywords": (
            "secret",
            "vault",
            "hashicorp_vault",
            "aws_secrets_manager",
            "azure_key_vault",
            "gcp_secret_manager",
            "doppler",
            "1password",
            "bitwarden",
            "sops",
            "age",
            "sealed_secret",
            "external_secrets",
            "infisical",
            "envkey",
            "chamber",
            "confidant",
            "credstash",
            "kms",
            "key_management",
            "key_rotation",
            "envelope_encryption",
        ),
        "file_patterns": ("vault*", "secret*", "kms*", "sops*", "sealed*"),
        "config_patterns": ("VAULT_", "KMS_", "SECRET_", "SOPS_", "AGE_", "KMS_"),
    },
    "audit_logging": {
        "layer": "security",
        "keywords": (
            "audit",
            "audit_log",
            "audit_trail",
            "compliance",
            "gdpr",
            "hipaa",
            "soc2",
            "iso27001",
            "pci_dss",
            "ccpa",
            "data_protection",
            "data_retention",
            "data_deletion",
            "right_to_be_forgotten",
            "consent",
            "privacy",
            "pii",
            "personal_data",
            "anonymization",
            "pseudonymization",
            "tokenization",
            "masking",
            "redaction",
        ),
        "file_patterns": ("audit*", "compliance*", "gdpr*", "privacy*", "pii*"),
        "config_patterns": ("AUDIT_", "COMPLIANCE_", "GDPR_", "HIPAA_", "PCI_"),
    },
    # ===================================================================
    # LAYER 9: DEPLOYMENT — CI/CD, Containers, K8s, IaC, Registries
    # ===================================================================
    "ci_cd_pipeline": {
        "layer": "deployment",
        "keywords": (
            "ci",
            "cd",
            "ci_cd",
            "pipeline",
            "build",
            "test",
            "deploy",
            "github_actions",
            "gitlab_ci",
            "jenkins",
            "circleci",
            "travis",
            "azure_pipelines",
            "bitbucket_pipelines",
            "drone",
            "woodpecker",
            "tekton",
            "argo",
            "argo_cd",
            "argo_rollouts",
            "argo_workflows",
            "flux",
            "fluxcd",
            "werf",
            "spinnaker",
            "harness",
            "codefresh",
            "semaphore",
            "buildkite",
            "teamcity",
            "bamboo",
            "concourse",
            "stage",
            "job",
            "step",
            "artifact",
            "cache",
            "matrix",
            "parallel",
            "timeout",
            "retry",
            "condition",
            "environment",
        ),
        "file_patterns": (
            ".github/workflows/*",
            ".gitlab-ci.yml",
            "jenkinsfile",
            "circleci*",
            "azure-pipelines*",
            "drone*",
            "tekton*",
            "argo*",
            "flux*",
        ),
        "config_patterns": (
            "CI_",
            "CD_",
            "BUILD_",
            "DEPLOY_",
            "GITHUB_ACTIONS_",
            "GITLAB_CI_",
        ),
    },
    "containerization": {
        "layer": "deployment",
        "keywords": (
            "docker",
            "dockerfile",
            "docker_compose",
            "compose",
            "container",
            "image",
            "layer",
            "base_image",
            "multi_stage",
            "buildkit",
            "buildx",
            "build_context",
            "cache_from",
            "target",
            "arg",
            "env",
            "volume",
            "port",
            "expose",
            "entrypoint",
            "cmd",
            "healthcheck",
            "user",
            "workdir",
            "copy",
            "add",
            "run",
        ),
        "file_patterns": (
            "dockerfile*",
            "docker-compose*",
            "compose*",
            "dockerignore*",
        ),
        "config_patterns": ("DOCKER_", "COMPOSE_", "CONTAINER_", "IMAGE_"),
    },
    "kubernetes": {
        "layer": "deployment",
        "keywords": (
            "kubernetes",
            "k8s",
            "kubectl",
            "helm",
            "helmfile",
            "kustomize",
            "pod",
            "deployment",
            "statefulset",
            "daemonset",
            "job",
            "cronjob",
            "service",
            "ingress",
            "configmap",
            "secret",
            "pvc",
            "pv",
            "storageclass",
            "namespace",
            "label",
            "annotation",
            "selector",
            "replica",
            "rollingupdate",
            "strategy",
            "readiness",
            "liveness",
            "startup",
            "probe",
            "resource",
            "limit",
            "request",
            "qos",
            "hpa",
            "vpa",
            "cronjob",
            "operator",
            "crd",
            "admission",
            "webhook",
            "mutating",
            "validating",
            "gateway_api",
        ),
        "file_patterns": (
            "k8s*",
            "kubernetes*",
            "helm*",
            "kustomize*",
            "manifest*",
            "*.yaml",
            "*.yml",
            "chart*",
            "values*",
        ),
        "config_patterns": ("KUBE_", "K8S_", "HELM_", "KUBECTL_", "KUSTOMIZE_"),
    },
    "iac": {
        "layer": "deployment",
        "keywords": (
            "terraform",
            "tf",
            "provider",
            "resource",
            "module",
            "data",
            "output",
            "variable",
            "locals",
            "backend",
            "state",
            "lock",
            "plan",
            "apply",
            "destroy",
            "import",
            "taint",
            "replace",
            "pulumi",
            "crossplane",
            "aws_cdk",
            "cdktf",
            "cdk8s",
            "cloudformation",
            "arm",
            "bicep",
            "ansible",
            "playbook",
            "role",
            "task",
            "handler",
            "inventory",
            "group_vars",
        ),
        "file_patterns": (
            "terraform*",
            "tf*",
            "pulumi*",
            "cdk*",
            "cloudformation*",
            "ansible*",
        ),
        "config_patterns": ("TERRAFORM_", "PULUMI_", "CDK_", "AWS_CDK_", "ANSIBLE_"),
    },
    "artifact_registry": {
        "layer": "deployment",
        "keywords": (
            "registry",
            "artifact",
            "package",
            "npm",
            "pypi",
            "maven",
            "gradle",
            "nuget",
            "cargo",
            "go_proxy",
            "docker_registry",
            "ghcr",
            "gcr",
            "ecr",
            "acr",
            "harbor",
            "jfrog",
            "artifactory",
            "nexus",
            "verdaccio",
            "gemfury",
            "packagecloud",
            "version",
            "semver",
            "tag",
            "release",
            "promote",
            "promote",
        ),
        "file_patterns": ("registry*", "artifact*", "package*", "release*"),
        "config_patterns": (
            "REGISTRY_",
            "ARTIFACT_",
            "PACKAGE_",
            "NPM_",
            "PYPI_",
            "MAVEN_",
        ),
    },
    # ===================================================================
    # LAYER 10: INTEGRATION — Webhooks, 3rd-party APIs, SDKs, Plugins
    # ===================================================================
    "webhook": {
        "layer": "integration",
        "keywords": (
            "webhook",
            "callback",
            "endpoint",
            "signature",
            "verification",
            "retry",
            "idempotency",
            "idempotency_key",
            "delivery",
            "attempt",
            "svix",
            "ngrok",
            "hookdeck",
            "webhook_relay",
            "ultrahook",
            "smee",
            "requestbin",
            "beeceptor",
            "webhook_site",
        ),
        "file_patterns": ("webhook*", "callback*", "hook*", "svix*"),
        "config_patterns": ("WEBHOOK_", "CALLBACK_", "SVIX_", "HOOKDECK_"),
    },
    "third_party_api": {
        "layer": "integration",
        "keywords": (
            "api_client",
            "sdk",
            "wrapper",
            "integration",
            "connector",
            "sendgrid",
            "mailgun",
            "postmark",
            "ses",
            "twilio",
            "plivo",
            "vonage",
            "slack",
            "discord",
            "teams",
            "telegram",
            "whatsapp",
            "salesforce",
            "hubspot",
            "pipedrive",
            "zendesk",
            "intercom",
            "stripe",
            "paypal",
            "plaid",
            "yodlee",
            "teller",
            "finicity",
            "aws_sdk",
            "boto3",
            "google_cloud_sdk",
            "azure_sdk",
        ),
        "file_patterns": ("client*", "sdk*", "integration*", "connector*", "webhook*"),
        "config_patterns": (
            "SENDGRID_",
            "MAILGUN_",
            "TWILIO_",
            "SLACK_",
            "SALESFORCE_",
            "STRIPE_",
            "PLAID_",
        ),
    },
    "plugin_system": {
        "layer": "integration",
        "keywords": (
            "plugin",
            "extension",
            "addon",
            "module",
            "hook",
            "filter",
            "action",
            "event",
            "listener",
            "subscriber",
            "publisher",
            "marketplace",
            "store",
            "registry",
            "manifest",
            "permission",
            "sandbox",
            "isolation",
            "wasm",
            "webassembly",
        ),
        "file_patterns": ("plugin*", "extension*", "addon*", "hook*", "marketplace*"),
        "config_patterns": ("PLUGIN_", "EXTENSION_", "MARKETPLACE_"),
    },
    # ===================================================================
    # LAYER 11: USER EXPERIENCE — i18n, a11y, Feature Flags, A/B Testing
    # ===================================================================
    "internationalization": {
        "layer": "user_experience",
        "keywords": (
            "i18n",
            "internationalization",
            "l10n",
            "localization",
            "locale",
            "language",
            "translation",
            "translate",
            "t",
            "gettext",
            "po",
            "pot",
            "mo",
            "xliff",
            "xlf",
            "json",
            "plural",
            "pluralization",
            "gender",
            "context",
            "interpolation",
            "date_format",
            "time_format",
            "number_format",
            "currency",
            "timezone",
            "rtl",
            "ltr",
            "direction",
        ),
        "file_patterns": (
            "i18n*",
            "l10n*",
            "locale*",
            "translation*",
            "lang*",
            "translations*",
        ),
        "config_patterns": ("I18N_", "L10N_", "LOCALE_", "TRANSLATION_", "LANG_"),
    },
    "accessibility": {
        "layer": "user_experience",
        "keywords": (
            "a11y",
            "accessibility",
            "wcag",
            "aria",
            "screen_reader",
            "keyboard_navigation",
            "focus",
            "tabindex",
            "role",
            "label",
            "alt_text",
            "contrast",
            "color_contrast",
            "font_size",
            "zoom",
            "magnification",
            "voiceover",
            "nvda",
            "jaws",
            "semantic_html",
            "landmark",
            "heading",
            "skip_link",
        ),
        "file_patterns": ("a11y*", "accessibility*", "aria*", "wcag*"),
        "config_patterns": ("A11Y_", "ACCESSIBILITY_", "ARIA_", "WCAG_"),
    },
    "ab_testing": {
        "layer": "user_experience",
        "keywords": (
            "ab_test",
            "a_b_test",
            "split_test",
            "experiment",
            "variant",
            "control",
            "treatment",
            "hypothesis",
            "significance",
            "p_value",
            "confidence_interval",
            "sample_size",
            "power",
            "conversion",
            "optimizely",
            "vwo",
            "google_optimize",
            "amplitude",
            "mixpanel",
            "posthog",
            "statsig",
            "growthbook",
            "feature_experiment",
        ),
        "file_patterns": (
            "ab_test*",
            "experiment*",
            "split_test*",
            "optimizely*",
            "vwo*",
        ),
        "config_patterns": (
            "AB_TEST_",
            "EXPERIMENT_",
            "OPTIMIZELY_",
            "VWO_",
            "AMPLITUDE_",
            "POSTHOG_",
        ),
    },
    "personalization": {
        "layer": "user_experience",
        "keywords": (
            "personalization",
            "recommendation",
            "recommender",
            "content",
            "user_segment",
            "cohort",
            "behavior",
            "preference",
            "interest",
            "collaborative_filtering",
            "content_based",
            "hybrid",
            "matrix_factorization",
            "ranking",
            "ranking_model",
            "embedding",
            "similarity",
        ),
        "file_patterns": (
            "personalization*",
            "recommendation*",
            "recommender*",
            "ranking*",
        ),
        "config_patterns": ("PERSONALIZATION_", "RECOMMENDATION_", "RANKING_"),
    },
    # ===================================================================
    # LAYER 12: GOVERNANCE — Rate Limiting, Quotas, Multi-tenancy, Compliance
    # ===================================================================
    "rate_limiting": {
        "layer": "governance",
        "keywords": (
            "rate_limit",
            "rate_limiter",
            "throttle",
            "throttling",
            "token_bucket",
            "leaky_bucket",
            "fixed_window",
            "sliding_window",
            "sliding_log",
            "gcra",
            "quota",
            "burst",
            "steady",
            "refill",
            "per_second",
            "per_minute",
            "per_hour",
            "per_day",
            "ip_limit",
            "user_limit",
            "api_key_limit",
            "global_limit",
            "redis_cell",
            "token_bucket",
            "leaky_bucket",
        ),
        "file_patterns": ("rate_limit*", "throttle*", "quota*", "throttle*"),
        "config_patterns": ("RATE_LIMIT_", "THROTTLE_", "QUOTA_", "BURST_", "RATE_"),
    },
    "multi_tenancy": {
        "layer": "governance",
        "keywords": (
            "tenant",
            "multi_tenant",
            "multi_tenancy",
            "saas",
            "b2b",
            "organization",
            "workspace",
            "project",
            "account",
            "team",
            "isolation",
            "data_isolation",
            "schema_per_tenant",
            "database_per_tenant",
            "shared_schema",
            "discriminator",
            "tenant_id",
            "tenant_slug",
            "subdomain",
            "custom_domain",
            "onboarding",
            "provisioning",
            "deprovisioning",
            "suspend",
        ),
        "file_patterns": ("tenant*", "organization*", "workspace*", "team*", "saas*"),
        "config_patterns": ("TENANT_", "ORGANIZATION_", "WORKSPACE_", "SAAS_"),
    },
    "quota_management": {
        "layer": "governance",
        "keywords": (
            "quota",
            "limit",
            "usage",
            "consumption",
            "entitlement",
            "allocation",
            "budget",
            "cap",
            "soft_limit",
            "hard_limit",
            "overage",
            "overage_charge",
            "warning",
            "alert",
            "notification",
            "reset",
            "period",
            "monthly",
            "quarterly",
            "annual",
            "rolling",
        ),
        "file_patterns": ("quota*", "limit*", "usage*", "entitlement*", "budget*"),
        "config_patterns": ("QUOTA_", "LIMIT_", "USAGE_", "ENTITLEMENT_", "BUDGET_"),
    },
    "compliance": {
        "layer": "governance",
        "keywords": (
            "compliance",
            "regulation",
            "policy",
            "standard",
            "framework",
            "gdpr",
            "hipaa",
            "soc2",
            "iso27001",
            "pci_dss",
            "ccpa",
            "lgpd",
            "pipeda",
            "ferpa",
            "coppa",
            "fisma",
            "fedramp",
            "audit",
            "evidence",
            "control",
            "requirement",
            "assessment",
            "gap",
            "remediation",
            "risk",
            "threat",
            "vulnerability",
        ),
        "file_patterns": ("compliance*", "policy*", "regulation*", "audit*", "risk*"),
        "config_patterns": (
            "COMPLIANCE_",
            "POLICY_",
            "REGULATION_",
            "GDPR_",
            "HIPAA_",
            "SOC2_",
        ),
    },
    # ===================================================================
    # ADDITIONAL COMPONENT TYPES TO REACH 80+
    # ===================================================================
    # Identity - additional
    "sso_saml": {
        "layer": "identity",
        "keywords": (
            "saml",
            "sso",
            "single_sign_on",
            "identity_provider",
            "idp",
            "service_provider",
            "sp",
            "assertion",
            "acs",
            "metadata",
            "entity_id",
            "name_id",
            "attribute",
            "binding",
            "redirect",
        ),
        "file_patterns": ("saml*", "sso*", "idp*", "sp*"),
        "config_patterns": ("SAML_", "SSO_", "IDP_", "SP_"),
    },
    "oauth2_provider": {
        "layer": "identity",
        "keywords": (
            "oauth2",
            "oauth",
            "authorization_server",
            "resource_server",
            "client_credentials",
            "authorization_code",
            "implicit",
            "pkce",
            "scope",
            "grant_type",
            "refresh_token",
            "access_token",
        ),
        "file_patterns": ("oauth*", "auth_server*", "resource_server*"),
        "config_patterns": ("OAUTH_", "OAUTH2_"),
    },
    "ldap_directory": {
        "layer": "identity",
        "keywords": (
            "ldap",
            "active_directory",
            "ad",
            "directory",
            "distinguished_name",
            "dn",
            "ou",
            "cn",
            "uid",
            "bind",
            "search_base",
            "group_of_names",
            "posix_group",
            "memberof",
            "samba",
        ),
        "file_patterns": ("ldap*", "ad*", "directory*"),
        "config_patterns": ("LDAP_", "AD_", "DIRECTORY_"),
    },
    "password_policy": {
        "layer": "identity",
        "keywords": (
            "password_policy",
            "password_strength",
            "min_length",
            "complexity",
            "expiration",
            "history",
            "reuse",
            "lockout",
            "failed_attempts",
            "breach_check",
            "haveibeenpwned",
            "zxcvbn",
        ),
        "file_patterns": ("password*", "policy*"),
        "config_patterns": ("PASSWORD_POLICY_", "PASSWORD_"),
    },
    # Transaction - additional
    "payment_method_storage": {
        "layer": "transaction",
        "keywords": (
            "payment_method",
            "card_token",
            "tokenization",
            "vault",
            "stripe_customer",
            "payment_method_id",
            "setup_intent",
            "confirm",
            "attach",
            "detach",
            "default_payment_method",
        ),
        "file_patterns": ("payment_method*", "token*", "vault*", "customer*"),
        "config_patterns": ("PAYMENT_METHOD_", "TOKEN_", "VAULT_"),
    },
    "fraud_prevention": {
        "layer": "transaction",
        "keywords": (
            "fraud",
            "risk",
            "radar",
            "signifyd",
            "kount",
            "sift",
            "velocity_check",
            "geo_check",
            "device_fingerprint",
            "chargeback",
            "dispute",
            "evidence",
            "representment",
        ),
        "file_patterns": ("fraud*", "risk*", "radar*", "chargeback*"),
        "config_patterns": ("FRAUD_", "RISK_", "RADAR_", "CHARGEBACK_"),
    },
    "payout_disbursement": {
        "layer": "transaction",
        "keywords": (
            "payout",
            "disbursement",
            "transfer",
            "bank_transfer",
            "ach",
            "wire",
            "sepa",
            "instant_payment",
            "faster_payments",
            "beneficiary",
            "routing_number",
            "account_number",
        ),
        "file_patterns": ("payout*", "disbursement*", "transfer*", "bank*"),
        "config_patterns": ("PAYOUT_", "DISBURSEMENT_", "ACH_", "WIRE_"),
    },
    # State - additional
    "session_replication": {
        "layer": "state",
        "keywords": (
            "session_replication",
            "sticky_session",
            "session_affinity",
            "cluster",
            "hazelcast",
            "infinispan",
            "redis_cluster",
            "session_failover",
            "session_backup",
            "distributed_session",
        ),
        "file_patterns": ("session*", "replication*", "cluster*"),
        "config_patterns": ("SESSION_REPLICATION_", "CLUSTER_", "HAZELCAST_"),
    },
    "rate_limit_state": {
        "layer": "state",
        "keywords": (
            "rate_limit_counter",
            "sliding_window",
            "token_bucket",
            "leaky_bucket",
            "fixed_window",
            "sliding_log",
            "gcra",
            "redis_cell",
            "throttle",
            "quota_tracker",
        ),
        "file_patterns": ("rate_limit*", "throttle*", "quota*", "bucket*"),
        "config_patterns": ("RATE_LIMIT_", "THROTTLE_", "QUOTA_", "BUCKET_"),
    },
    "configuration_cache": {
        "layer": "state",
        "keywords": (
            "config_cache",
            "feature_flag_cache",
            "remote_config",
            "firebase_remote_config",
            "launchdarkly_cache",
            "split_cache",
            "config_refresh",
            "cache_warming",
            "cache_invalidation",
        ),
        "file_patterns": ("config*", "remote_config*", "feature_flag*"),
        "config_patterns": ("CONFIG_CACHE_", "REMOTE_CONFIG_", "FF_CACHE_"),
    },
    # Data - additional
    "timeseries_database": {
        "layer": "data",
        "keywords": (
            "timeseries",
            "influxdb",
            "timescaledb",
            "prometheus",
            "victoriametrics",
            "questdb",
            "tdengine",
            "databend",
            "retention",
            "downsampling",
            "continuous_aggregate",
            "compression",
            "chunk",
            "hypertable",
        ),
        "file_patterns": ("timeseries*", "influx*", "timescale*", "victoria*"),
        "config_patterns": ("INFLUX_", "TIMESCALE_", "VICTORIA_", "TIMESERIES_"),
    },
    "graph_database": {
        "layer": "data",
        "keywords": (
            "neo4j",
            "graphdb",
            "janusgraph",
            "tigergraph",
            "arangodb",
            "dgraph",
            "orientdb",
            "cypher",
            "gremlin",
            "sparql",
            "node",
            "edge",
            "relationship",
            "property",
            "traversal",
        ),
        "file_patterns": ("neo4j*", "graph*", "cypher*", "gremlin*"),
        "config_patterns": ("NEO4J_", "GRAPH_", "CYPHER_", "GREMLIN_"),
    },
    "data_lake": {
        "layer": "data",
        "keywords": (
            "datalake",
            "data_lake",
            "delta_lake",
            "iceberg",
            "hudi",
            "parquet",
            "avro",
            "orc",
            "partition",
            "compaction",
            "schema_evolution",
            "time_travel",
            "vacuum",
            "optimize",
        ),
        "file_patterns": ("datalake*", "delta*", "iceberg*", "hudi*"),
        "config_patterns": ("DELTA_", "ICEBERG_", "HUDI_", "DATALAKE_"),
    },
    "streaming_platform": {
        "layer": "data",
        "keywords": (
            "kafka",
            "pulsar",
            "redpanda",
            "kinesis",
            "pubsub",
            "event_hub",
            "flink",
            "spark_streaming",
            "ksql",
            "stream_processing",
            "window",
            "watermark",
            "late_data",
        ),
        "file_patterns": ("streaming*", "flink*", "ksql*", "spark*"),
        "config_patterns": ("KAFKA_", "PULSAR_", "FLINK_", "KINESIS_"),
    },
    # Communication - additional
    "webhook_receiver": {
        "layer": "communication",
        "keywords": (
            "webhook",
            "callback",
            "endpoint",
            "signature_verification",
            "retry_policy",
            "idempotency_key",
            "delivery_receipt",
            "svix",
            "ngrok",
            "webhook_relay",
            "ultrahook",
            "smee",
        ),
        "file_patterns": ("webhook*", "callback*", "hook*", "svix*"),
        "config_patterns": ("WEBHOOK_", "CALLBACK_", "SVIX_", "HOOKDECK_"),
    },
    "event_bus": {
        "layer": "communication",
        "keywords": (
            "event_bus",
            "event_emitter",
            "event_dispatcher",
            "mediator",
            "pubsub",
            "publish_subscribe",
            "domain_event",
            "integration_event",
            "outbox_pattern",
            "transactional_outbox",
            "cdc",
        ),
        "file_patterns": ("event_bus*", "event_emitter*", "mediator*", "outbox*"),
        "config_patterns": ("EVENT_BUS_", "EVENT_", "OUTBOX_", "CDC_"),
    },
    "service_mesh": {
        "layer": "communication",
        "keywords": (
            "istio",
            "linkerd",
            "consul",
            "service_mesh",
            "sidecar",
            "mtls",
            "mutual_tls",
            "traffic_split",
            "canary",
            "mirror",
            "fault_injection",
            "timeout",
            "retry",
            "circuit_breaker",
        ),
        "file_patterns": ("istio*", "linkerd*", "consul*", "mesh*", "sidecar*"),
        "config_patterns": ("ISTIO_", "LINKERD_", "CONSUL_", "MESH_", "MTLS_"),
    },
    # Delivery - additional
    "edge_computing": {
        "layer": "delivery",
        "keywords": (
            "edge",
            "edge_computing",
            "cloudflare_workers",
            "vercel_edge",
            "netlify_edge",
            "aws_lambda_edge",
            "fastly_compute",
            "edge_function",
            "edge_middleware",
            "geo_routing",
        ),
        "file_patterns": ("edge*", "worker*", "middleware*"),
        "config_patterns": ("EDGE_", "WORKER_", "CLOUDFLARE_WORKER_"),
    },
    "service_discovery": {
        "layer": "delivery",
        "keywords": (
            "service_discovery",
            "consul",
            "etcd",
            "eureka",
            "nacos",
            "zookeeper",
            "dns",
            "srv_record",
            "health_check",
            "deregistration",
            "registration",
            "catalog",
        ),
        "file_patterns": ("discovery*", "consul*", "etcd*", "eureka*"),
        "config_patterns": ("CONSUL_", "ETCD_", "EUREKA_", "NACOS_", "DISCOVERY_"),
    },
    # Observability - additional
    "log_aggregation": {
        "layer": "observability",
        "keywords": (
            "fluentd",
            "fluentbit",
            "logstash",
            "vector",
            "filebeat",
            "elasticsearch",
            "opensearch",
            "loki",
            "graylog",
            "syslog",
            "json_log",
            "structured_log",
            "log_rotation",
            "retention",
            "compression",
            "shipping",
        ),
        "file_patterns": ("log*", "fluent*", "logstash*", "vector*", "loki*"),
        "config_patterns": ("FLUENT_", "LOGSTASH_", "VECTOR_", "LOKI_", "ELASTIC_"),
    },
    "synthetics_monitoring": {
        "layer": "observability",
        "keywords": (
            "synthetic",
            "uptime",
            "pingdom",
            "uptimerobot",
            "statuscake",
            "checkly",
            "better_uptime",
            "cronitor",
            "healthchecks_io",
            "heartbeat",
            "cron",
            "schedule",
            "assertion",
            "threshold",
        ),
        "file_patterns": ("synthetic*", "uptime*", "healthcheck*", "monitor*"),
        "config_patterns": ("SYNTHETIC_", "UPTIME_", "PINGDOM_", "HEALTHCHECK_"),
    },
    "rum": {
        "layer": "observability",
        "keywords": (
            "rum",
            "real_user_monitoring",
            "web_vitals",
            "core_web_vitals",
            "lcp",
            "fid",
            "cls",
            "ttfb",
            "fcp",
            "tti",
            "datadog_rum",
            "newrelic_browser",
            "elastic_rum",
            "sentry_replay",
        ),
        "file_patterns": ("rum*", "web_vitals*", "browser*"),
        "config_patterns": ("RUM_", "WEB_VITALS_", "DATADOG_RUM_", "SENTRY_REPLAY_"),
    },
    # Security - additional
    "csp": {
        "layer": "security",
        "keywords": (
            "csp",
            "content_security_policy",
            "nonce",
            "hash",
            "script_src",
            "style_src",
            "img_src",
            "connect_src",
            "font_src",
            "frame_src",
            "object_src",
            "base_uri",
            "report_uri",
            "report_to",
            "upgrade_insecure_requests",
        ),
        "file_patterns": ("csp*", "content_security*", "nonce*"),
        "config_patterns": ("CSP_", "CONTENT_SECURITY_"),
    },
    "rate_limiting_security": {
        "layer": "security",
        "keywords": (
            "rate_limit",
            "throttle",
            "ddos",
            "bot_detection",
            "cloudflare_bot_fight_mode",
            "recaptcha",
            "hcaptcha",
            "turnstile",
            "friendly_captcha",
            "arkose_labs",
            "ip_reputation",
            "geo_blocking",
            "asn_blocking",
        ),
        "file_patterns": ("rate_limit*", "ddos*", "bot*", "recaptcha*", "captcha*"),
        "config_patterns": ("RATE_LIMIT_", "DDOS_", "BOT_", "RECAPTCHA_", "CAPTCHA_"),
    },
    "api_security": {
        "layer": "security",
        "keywords": (
            "api_security",
            "openapi_security",
            "oauth2_security",
            "api_key_validation",
            "jwt_validation",
            "scope_validation",
            "rate_limit",
            "quota",
            "api_gateway_security",
            "mutation_testing",
            "fuzzing",
            "sast",
            "dast",
            "sca",
        ),
        "file_patterns": ("api_security*", "openapi*", "sast*", "dast*", "sca*"),
        "config_patterns": (
            "API_SECURITY_",
            "OPENAPI_SECURITY_",
            "SAST_",
            "DAST_",
            "SCA_",
        ),
    },
    # Deployment - additional
    "gitops": {
        "layer": "deployment",
        "keywords": (
            "gitops",
            "flux",
            "argo_cd",
            "argocd",
            "fluxcd",
            "kustomize",
            "helm",
            "helmfile",
            "kpt",
            "kptfn",
            "reconcile",
            "sync",
            "drift_detection",
            "automated_sync",
        ),
        "file_patterns": ("flux*", "argocd*", "kustomize*", "helmfile*", "gitops*"),
        "config_patterns": ("FLUX_", "ARGOCD_", "GITOPS_", "KUSTOMIZE_"),
    },
    "chaos_engineering": {
        "layer": "deployment",
        "keywords": (
            "chaos",
            "chaos_engineering",
            "chaos_mesh",
            "litmus",
            "gremlin",
            "powerfulseal",
            "pumba",
            "kube_monkey",
            "fault_injection",
            "latency",
            "packet_loss",
            "kill_pod",
            "network_partition",
            "cpu_stress",
            "memory_stress",
        ),
        "file_patterns": ("chaos*", "litmus*", "chaos_mesh*", "gremlin*"),
        "config_patterns": ("CHAOS_", "LITMUS_", "CHAOS_MESH_", "GREMLIN_"),
    },
    "blue_green_deployment": {
        "layer": "deployment",
        "keywords": (
            "blue_green",
            "canary",
            "rolling",
            "rolling_update",
            "strategy",
            "max_surge",
            "max_unavailable",
            "pause",
            "rollback",
            "promote",
            "switch",
            "traffic_split",
        ),
        "file_patterns": ("blue_green*", "canary*", "strategy*", "rollout*"),
        "config_patterns": ("BLUE_GREEN_", "CANARY_", "ROLLOUT_", "STRATEGY_"),
    },
    # Integration - additional
    "marketplace": {
        "layer": "integration",
        "keywords": (
            "marketplace",
            "app_store",
            "extension_store",
            "plugin_store",
            "listing",
            "review",
            "rating",
            "install",
            "uninstall",
            "manifest",
            "permissions",
            "scopes",
            "oauth",
        ),
        "file_patterns": ("marketplace*", "store*", "extension*", "plugin*"),
        "config_patterns": ("MARKETPLACE_", "STORE_", "EXTENSION_"),
    },
    "data_synchronization": {
        "layer": "integration",
        "keywords": (
            "sync",
            "synchronization",
            "cdc",
            "change_data_capture",
            "debezium",
            "airbyte",
            "fivetran",
            "stitch",
            "matillion",
            "incremental",
            "full_refresh",
            "upsert",
            "merge",
        ),
        "file_patterns": ("sync*", "cdc*", "debezium*", "airbyte*", "fivetran*"),
        "config_patterns": ("SYNC_", "CDC_", "DEBEZIUM_", "AIRBYTE_", "FIVETRAN_"),
    },
    # User Experience - additional
    "analytics": {
        "layer": "user_experience",
        "keywords": (
            "analytics",
            "tracking",
            "event",
            "pageview",
            "session",
            "user_id",
            "anonymous_id",
            "identify",
            "track",
            "page",
            "segment",
            "mixpanel",
            "amplitude",
            "posthog",
            "heap",
            "ga",
            "google_analytics",
            "gtm",
            "tag_manager",
        ),
        "file_patterns": (
            "analytics*",
            "tracking*",
            "segment*",
            "mixpanel*",
            "amplitude*",
        ),
        "config_patterns": (
            "ANALYTICS_",
            "SEGMENT_",
            "MIXPANEL_",
            "AMPLITUDE_",
            "POSTHOG_",
            "GA_",
        ),
    },
    "feature_analytics": {
        "layer": "user_experience",
        "keywords": (
            "feature_usage",
            "adoption",
            "engagement",
            "retention",
            "churn",
            "cohort",
            "funnel",
            "conversion",
            "drop_off",
            "heatmap",
            "session_replay",
            "clickstream",
            "rage_click",
        ),
        "file_patterns": ("feature_usage*", "adoption*", "engagement*", "funnel*"),
        "config_patterns": ("FEATURE_USAGE_", "ADOPTION_", "ENGAGEMENT_", "FUNNEL_"),
    },
    # Governance - additional
    "data_governance": {
        "layer": "governance",
        "keywords": (
            "data_governance",
            "data_catalog",
            "data_lineage",
            "data_quality",
            "metadata",
            "schema_registry",
            "great_expectations",
            "monte_carlo",
            "datafold",
            "dbt",
            "lineage",
            "ownership",
            "stewardship",
            "classification",
            "tagging",
            "glossary",
        ),
        "file_patterns": (
            "governance*",
            "catalog*",
            "lineage*",
            "quality*",
            "metadata*",
        ),
        "config_patterns": (
            "GOVERNANCE_",
            "CATALOG_",
            "LINEAGE_",
            "QUALITY_",
            "METADATA_",
        ),
    },
    "cost_management": {
        "layer": "governance",
        "keywords": (
            "cost",
            "billing",
            "finops",
            "cloud_cost",
            "optimization",
            "rightsizing",
            "reserved_instance",
            "savings_plan",
            "budget",
            "alert",
            "anomaly",
            "forecast",
            "allocation",
            "showback",
            "chargeback",
            "tagging",
            "cost_center",
        ),
        "file_patterns": ("cost*", "finops*", "budget*", "billing*", "optimization*"),
        "config_patterns": ("COST_", "FINOPS_", "BUDGET_", "BILLING_", "OPTIMIZATION_"),
    },
}

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_taxonomy() -> None:
    """Validate the taxonomy structure."""
    layers_found = set()
    for comp_type, info in INFRASTRUCTURE_TAXONOMY.items():
        assert "layer" in info, f"{comp_type}: missing layer"
        assert (
            info["layer"] in INFRASTRUCTURE_LAYERS
        ), f"{comp_type}: invalid layer {info['layer']}"
        assert "keywords" in info, f"{comp_type}: missing keywords"
        assert len(info["keywords"]) >= 5, f"{comp_type}: need at least 5 keywords"
        assert "file_patterns" in info, f"{comp_type}: missing file_patterns"
        assert "config_patterns" in info, f"{comp_type}: missing config_patterns"
        layers_found.add(info["layer"])

    missing_layers = set(INFRASTRUCTURE_LAYERS) - layers_found
    assert not missing_layers, f"Layers not covered: {missing_layers}"

    # Should have at least 5 component types per layer
    for layer in INFRASTRUCTURE_LAYERS:
        count = sum(
            1 for info in INFRASTRUCTURE_TAXONOMY.values() if info["layer"] == layer
        )
        assert (
            count >= 5
        ), f"Layer {layer} has only {count} component types, need at least 5"

    print(
        f"✓ Taxonomy validated: {len(INFRASTRUCTURE_TAXONOMY)} component types across {len(layers_found)} layers"
    )


if __name__ == "__main__":
    validate_taxonomy()
    print(f"Total component types: {len(INFRASTRUCTURE_TAXONOMY)}")
    for layer in INFRASTRUCTURE_LAYERS:
        count = sum(
            1 for info in INFRASTRUCTURE_TAXONOMY.values() if info["layer"] == layer
        )
        print(f"  {layer}: {count} types")
