#!/usr/bin/env python3
"""Validate commit messages against the Conventional Commits specification.

Why this exists rather than a dependency
----------------------------------------
Options evaluated in docs/audits/2026-09-17-phase-1-5-sota-comparison.md:

  * `commitizen` -- actively maintained (4.18.1, 2026-09-13) and would work.
    Its `check` subcommand validates the SAME header-only subset implemented
    here; the parts it adds (changelog generation, version bumping, an
    interactive `cz commit` prompt) are machinery this repository does not
    use. Adopting it would add a runtime dependency chain to enforce the
    header, which is a NetCDF-grade cost for the narrow requirement.

  * `gitlint` -- REJECTED. PyPI shows 0.19.1 uploaded 2023-03-10, roughly
    3.5 years stale at the time of writing, with no release since.

  * The PyPI package named `commitlint` -- REJECTED, and flagged as a TRAP.
    It is a different project under GPL-3.0. Anyone reaching for the familiar
    "commitlint" name lands on it and takes on a copyleft dependency they did
    not intend. The requirement is Conventional Commits, not the commitlint
    brand.

  * `conform` (the Go tool GitHub and many others use) -- a compiled binary,
    so it cannot be pinned by the Python toolchain, and it has been
    effectively unmaintained; a maintained fork exists (`go-conventional-commits`).

WHAT IS VALIDATED, AND WHAT IS DELIBERATELY NOT
-----------------------------------------------
The HEADER only. The specification is genuinely ambiguous about body and
footer structure -- its own issue tracker records unresolved questions about
footers without a body and about whether `!` implies a breaking change -- so
enforcing more than the header would encode one reading of an ambiguous
document as if it were the document. That decision is recorded as AR-003.

Deliberately NOT enforced:
  * lowercase subject -- not a rule in the specification, and the popular
    commitlint config that popularised it is a config choice, not the spec;
  * a maximum subject length -- a widely copied 72-char rule is convention,
    not spec (a warning is emitted, never a failure);
  * a required scope, or a scope allow-list -- the spec makes scope optional,
    and this repository's changes frequently span several areas;
  * `Signed-off-by` -- not part of the specification.

The one structural rule that IS enforced is the blank line between the header
and the body, because getting it wrong silently changes what `git log
--oneline`, `git rebase -i` and every changelog generator display -- the
header stops being the first paragraph.

Escape hatch: a header whose first line contains `[skip commit-msg]` is
accepted with a warning, so a legitimate exception (a revert of a revert, an
imported upstream commit) is possible without disabling the hook. It is a
VISIBLE marker in the message, not a silent bypass.

Charter references: §4, §13, §20, §28.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass

# The spec's type vocabulary is open ("feat", "fix" and "others are allowed"),
# so this is a WARNING list, not a rejection list. It matches the conventional
# set including the Angular additions this repository is likely to use.
KNOWN_TYPES = frozenset(
    {
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
    }
)

# type(scope)!: description
#   type        required, lower-case word
#   (scope)     optional, may contain hyphens, dots, slashes, spaces
#   !           optional breaking-change marker
#   description required, non-empty
HEADER_RE = re.compile(
    r"^(?P<type>[a-zA-Z]+)"
    r"(?:\((?P<scope>[^()]+)\))?"
    r"(?P<breaking>!)?"
    r": (?P<description>.+)$"
)

SUBJECT_WARN_LENGTH = 72
SKIP_MARKER = "[skip commit-msg]"

# Merge commits are generated by git and are not subject to this convention.
MERGE_RE = re.compile(r"^Merge ")

# The commit that introduces this checker cannot satisfy it retroactively, and
# neither can commits made before the hook was installed. Only the range being
# pushed is checked, so history is never rewritten to satisfy a new rule.
REVERT_RE = re.compile(r"^Revert ")


@dataclass(frozen=True)
class Finding:
    """One problem with one commit message."""

    commit: str
    severity: str  # "error" | "warning"
    message: str


def _git(*args: str) -> str:
    """Run a git command and return stdout, raising on failure."""
    proc = subprocess.run(  # noqa: S603 - fixed argv, no shell, no user input
        # "git" is resolved through PATH deliberately: this must use the same
        # git the developer is using.
        ["git", *args],  # noqa: S607
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        msg = f"git {' '.join(args)} failed: {proc.stderr.strip()}"
        raise RuntimeError(msg)
    return proc.stdout


def _commits_in_range(rev_range: str) -> list[tuple[str, str]]:
    """Return (sha, full_message) for each commit in a revision range.

    A range like `BASE..HEAD` excludes BASE and includes HEAD, which is what
    a pre-push or PR check wants. `--no-merges` is NOT used: merge commits are
    filtered by content below so the reason is visible in one place.
    """
    raw = _git("log", "--format=%H%x00%B%x00%x1e", rev_range)
    entries: list[tuple[str, str]] = []
    for record in raw.split("\x1e"):
        record = record.strip("\n")
        if not record.strip():
            continue
        parts = record.split("\x00")
        if len(parts) < 2:
            continue
        sha = parts[0].strip()
        message = parts[1]
        if sha:
            entries.append((sha, message))
    return entries


def check_message(sha: str, message: str) -> list[Finding]:
    """Validate one commit message, returning its findings."""
    findings: list[Finding] = []
    short = sha[:8]

    lines = message.splitlines()
    if not lines:
        return [Finding(short, "error", "commit message is empty")]

    header = lines[0].rstrip()

    if SKIP_MARKER in header:
        findings.append(
            Finding(
                short,
                "warning",
                f"header contains {SKIP_MARKER}; conventional-commit format "
                f"not enforced for this commit.",
            )
        )
        return findings

    if MERGE_RE.match(header):
        return findings

    if REVERT_RE.match(header):
        # `Revert "..."` is git's own format and carries its own meaning.
        return findings

    # --- Header shape -----------------------------------------------------
    match = HEADER_RE.match(header)
    if not match:
        findings.append(
            Finding(
                short,
                "error",
                f"header is not `type(scope): description` -- got {header!r}. "
                f"The specification requires a type, an optional scope, and a "
                f"non-empty description separated from the type by ':' + space.",
            )
        )
    else:
        commit_type = match.group("type")
        description = match.group("description").strip()

        if commit_type != commit_type.lower():
            findings.append(
                Finding(
                    short,
                    "error",
                    f"type {commit_type!r} must be lower-case",
                )
            )

        if commit_type.lower() not in KNOWN_TYPES:
            # A warning: the specification explicitly permits types beyond
            # "feat" and "fix".
            findings.append(
                Finding(
                    short,
                    "warning",
                    f"type {commit_type!r} is not in the conventional set "
                    f"({', '.join(sorted(KNOWN_TYPES))}). Allowed, but check "
                    f"it is not a typo.",
                )
            )

        if not description:
            findings.append(Finding(short, "error", "description is empty"))

        if len(header) > SUBJECT_WARN_LENGTH:
            findings.append(
                Finding(
                    short,
                    "warning",
                    f"header is {len(header)} characters "
                    f"(> {SUBJECT_WARN_LENGTH}); long subjects are truncated "
                    f"in most log views. Not an error -- it is convention, "
                    f"not specification.",
                )
            )

    # --- Body separation --------------------------------------------------
    #
    # The one structural rule enforced. Without a blank line the header stops
    # being the first paragraph, and `git log --oneline`, `rebase -i` and
    # changelog generators all display something different from what was
    # intended.
    if len(lines) > 1 and lines[1].strip():
        findings.append(
            Finding(
                short,
                "error",
                "line 2 is not blank. The specification requires a blank line "
                "between the header and the body; without it the header is no "
                "longer the first paragraph and tooling that reads paragraph "
                "one sees the wrong text.",
            )
        )

    return findings


def _default_range() -> str:
    """Pick a sensible range when none is given.

    On a branch with an upstream, check what is not yet pushed. Otherwise
    check the tip. Never check the entire history: that would fail on commits
    made before this convention existed, and the only fixes would be rewriting
    history (forbidden, §28) or disabling the check.
    """
    try:
        _git("rev-parse", "--verify", "--quiet", "@{upstream}")
    except RuntimeError:
        return "HEAD~1..HEAD"
    return "@{upstream}..HEAD"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate commit messages against Conventional Commits."
    )
    parser.add_argument(
        "--range",
        dest="rev_range",
        help="git revision range to check (default: unpushed commits, else HEAD)",
    )
    parser.add_argument(
        "--message-file",
        help="validate a single message file (as the commit-msg hook receives)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="treat warnings as failures",
    )
    args = parser.parse_args(argv)

    findings: list[Finding] = []

    if args.message_file:
        from pathlib import Path

        path = Path(args.message_file)
        if not path.exists():
            print(
                f"check_commit_msg: message file {path} does not exist.",
                file=sys.stderr,
            )
            return 1
        findings = check_message("working", path.read_text(encoding="utf-8"))
    else:
        rev_range = args.rev_range or _default_range()
        try:
            commits = _commits_in_range(rev_range)
        except RuntimeError as exc:
            # An unresolvable range is a real failure, not a pass: silently
            # skipping would mean the gate reports success having checked
            # nothing.
            print(f"check_commit_msg: {exc}", file=sys.stderr)
            return 1
        if not commits:
            print(f"check_commit_msg: no commits in range {rev_range!r}.")
            return 0
        for sha, message in commits:
            findings.extend(check_message(sha, message))

    errors = [f for f in findings if f.severity == "error"]
    warnings = [f for f in findings if f.severity == "warning"]

    for finding in warnings:
        print(f"check_commit_msg: WARNING {finding.commit}: {finding.message}")
    for finding in errors:
        print(
            f"check_commit_msg: ERROR {finding.commit}: {finding.message}",
            file=sys.stderr,
        )

    if errors or (args.strict and warnings):
        total = len(errors) + (len(warnings) if args.strict else 0)
        print(
            f"\ncheck_commit_msg: {total} problem(s). "
            f"Format: `type(scope): description` -- see "
            f"https://www.conventionalcommits.org/",
            file=sys.stderr,
        )
        print(
            "  Escape hatch: include the literal marker "
            f"`{SKIP_MARKER}` in the header (visible in the log).",
            file=sys.stderr,
        )
        return 1

    if not args.message_file:
        print(f"check_commit_msg: checked {len(commits)} commit message(s); no errors.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
