"""Render the study report — the deliverable of a study.

WHAT A REPORT IS FOR
--------------------
A report is read by a human or agent session that then decides whether anything
is worth adopting. Its job is therefore to make the **evidence** legible and to
be explicit about what it does not know.

Two rules follow from that, and both are enforced in code rather than left to
the writer:

1. **Every structural claim carries its depth limit.** The pipeline produces a
   structural map; it does not understand the code. A report that said "this
   project implements retrieval" would be an overclaim. It says "retrieval
   directories are present: `src/pkg/retrieval/`", which a reader can check.

2. **`code_reused` is always false, and says why.** Not because the pipeline
   promises restraint, but because it has no code path that writes source into
   `catalog/` (ADR-0021 Decision 2). The field is emitted from a constant so it
   cannot be set differently per study.

The report deliberately does NOT contain a summary judgement. "Is this pattern
worth adopting?" is a `DESIGN OPINION`, which belongs to a session that has read
the code, not to a script that counted directories (charter §6).
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from study_pipeline import __version__
from study_pipeline.classify import Classification, Taxonomy
from study_pipeline.inventory import Inventory
from study_pipeline.patterns import Candidate, Confidence

#: Emitted verbatim in every report. A constant, not a parameter, so no caller
#: can produce a report claiming reuse (ADR-0021 Decision 2).
CODE_REUSED: Final = False

#: Where reports are written, relative to the repository root.
REPORTS_DIRNAME: Final = "study_pipeline/studied_repos"

#: Confidence labels mapped to how a reader should treat them. The wording is
#: the point: "strong" for a directory name would invite exactly the over-trust
#: this vocabulary exists to prevent.
CONFIDENCE_MEANING: Final[dict[Confidence, str]] = {
    Confidence.STRONG: (
        "Two independent lines of evidence (multiple module-bearing "
        "directories, or a directory plus a declared dependency)."
    ),
    Confidence.MODERATE: (
        "One line of evidence: a module-bearing directory, or a declared "
        "dependency by itself."
    ),
    Confidence.WEAK: (
        "A conventional directory or file name only. This may be a real "
        "abstraction, a stub, or an empty placeholder — the name cannot "
        "distinguish them."
    ),
}


@dataclass(frozen=True, slots=True)
class StudyReport:
    """Everything a report needs, gathered before rendering."""

    slug: str
    url: str
    commit: str
    studied_on: str
    size_bytes: int
    inventory: Inventory
    candidates: tuple[Candidate, ...]
    classifications: tuple[Classification, ...]
    taxonomy: Taxonomy
    #: Set when the study could not complete, so a partial report is honest
    #: about being partial rather than looking like a thin result.
    incomplete_reason: str = ""

    @property
    def filename(self) -> str:
        """`<project>.md`, per the studied_repos README's naming rule."""
        return f"{self.slug.rsplit('__', 1)[-1]}.md"


def _human_bytes(count: int) -> str:
    """Format a byte count for a report header."""
    size = float(count)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if size < 1024 or unit == "GiB":
            return f"{size:.1f} {unit}" if unit != "B" else f"{int(size)} B"
        size /= 1024
    return f"{size:.1f} GiB"  # pragma: no cover - unreachable


def _evidence_lines(candidate: Candidate) -> list[str]:
    """Render a candidate's evidence as a bullet list."""
    if not candidate.evidence_paths:
        return ["- (no evidence paths — this candidate should not be reported)"]
    return [f"- `{path}`" for path in candidate.evidence_paths]


def _render_header(report: StudyReport) -> list[str]:
    return [
        f"# {report.slug.rsplit('__', 1)[-1]}",
        "",
        "> **Generated by the study pipeline.** This is a *structural* analysis: it",
        "> reads file names, paths and manifests. It does not execute the studied",
        "> code, does not import it, and does not read every source file. Statements",
        "> below are observations about structure unless labelled otherwise",
        "> (charter §6).",
        "",
        "| | |",
        "|---|---|",
        f"| Repository | {report.url} |",
        f"| Commit | `{report.commit}` |",
        f"| Studied | {report.studied_on} |",
        f"| Clone size | {_human_bytes(report.size_bytes)} |",
        f"| Files | {report.inventory.total_files} |",
        f"| Dominant language | {report.inventory.primary_language} |",
        f"| Test files | {report.inventory.test_file_count} in "
        f"{len(report.inventory.test_dirs)} directory(ies) |",
        (
            f"| Declared dependencies | {len(report.inventory.declared_dependencies)} "
            "(root manifest only — see notes) |"
            if report.inventory.notes
            else f"| Declared dependencies | {len(report.inventory.declared_dependencies)} |"
        ),
        f"| Pipeline version | {__version__} |",
        f"| `code_reused` | `{str(CODE_REUSED).lower()}` |",
        "",
    ]


def _render_provenance(report: StudyReport) -> list[str]:
    return [
        "## Provenance",
        "",
        f"Studied at commit `{report.commit}`. Every statement in this report",
        "refers to that commit and may be false at another.",
        "",
        "**No code was reused.** `code_reused: false` is not a promise about the",
        "pipeline's restraint — it is structural. The pipeline writes Markdown",
        "reports and has no code path that writes into `catalog/` or",
        "`integrations/` (charter §11, ADR-0021 Decision 2).",
        "",
        "**No code was executed.** The studied repository was cloned and read. It",
        "was never imported, never installed, and no subprocess ran inside it",
        "(ADR-0021 Decision 1).",
        "",
    ]


def _render_limitations(report: StudyReport) -> list[str]:
    inventory = report.inventory
    lines = [
        "## What this report cannot tell you",
        "",
        "These are limits of the method, not of the studied project. Read them",
        "before drawing conclusions from the sections below.",
        "",
        "- **Dependency count is declared, not resolved.** It counts requirement",
        "  strings in root manifests. Nothing was fetched, so a directive with 14",
        "  declared dependencies may install 60 packages.",
        "- **Test count is files, not tests.** Counting actual tests requires",
        "  running them, which the pipeline does not do.",
        "- **Pattern detection matches names and manifests.** A pattern",
        "  implemented across files without a directory named after it will be",
        "  missed entirely. Confidence labels the evidence, not the importance.",
        "- **Nothing here is a judgement of quality.** A directory being present",
        "  says nothing about whether the code inside it is good.",
        "",
    ]
    if inventory.notes:
        lines.extend(["### Notes from this run", ""])
        lines.extend(f"- {note}" for note in inventory.notes)
        lines.append("")
    if report.incomplete_reason:
        lines.extend(
            [
                "### ⚠ This study is incomplete",
                "",
                f"{report.incomplete_reason}",
                "",
            ]
        )
    return lines


def _render_structure(report: StudyReport) -> list[str]:
    inventory = report.inventory
    lines = ["## Structure", "", "### Top level", ""]
    lines.extend(f"- `{entry}`" for entry in inventory.top_level_entries[:40])
    if len(inventory.top_level_entries) > 40:
        lines.append(f"- … and {len(inventory.top_level_entries) - 40} more")
    lines.append("")

    if inventory.packages:
        lines.extend(["### Packages", ""])
        lines.extend(f"- `{package}`" for package in inventory.packages[:20])
        lines.append("")

    if inventory.extension_counts:
        lines.extend(
            ["### File counts by extension", "", "| Extension | Files |", "|---|---|"]
        )
        for extension, count in list(inventory.extension_counts.items())[:15]:
            lines.append(f"| `{extension}` | {count} |")
        lines.append("")

    if inventory.markers:
        lines.extend(["### Build, test and governance markers", ""])
        for group, names in sorted(inventory.markers.items()):
            rendered = ", ".join(f"`{name}`" for name in names)
            lines.append(f"- **{group}**: {rendered}")
        lines.append("")

    return lines


def _render_dependencies(report: StudyReport) -> list[str]:
    inventory = report.inventory
    if not inventory.manifests and not inventory.declared_dependencies:
        return [
            "## Declared dependencies",
            "",
            "No root manifest was recognised. This project may declare its",
            "dependencies in a file the pipeline does not read, or have none.",
            "",
        ]

    lines = ["## Declared dependencies", ""]
    for manifest in inventory.manifests:
        lines.append(f"### `{manifest.path}`")
        lines.append("")
        if manifest.error:
            lines.append(f"⚠ Could not parse: {manifest.error}")
            lines.append("")
            continue
        if not manifest.requirements:
            lines.append("No requirements declared.")
            lines.append("")
            continue
        lines.extend(f"- `{requirement}`" for requirement in manifest.requirements)
        lines.append("")
    return lines


def _render_findings(report: StudyReport) -> list[str]:
    lines = [
        "## Candidate patterns",
        "",
        "Every candidate below is a **structural observation** with its evidence",
        "and confidence stated. None is a recommendation — deciding whether a",
        "pattern is worth adopting is a design opinion that requires reading the",
        "code, which this pipeline does not do.",
        "",
    ]

    if not report.candidates:
        lines.extend(
            [
                "No conventional infrastructure patterns were detected.",
                "",
                "**This is a real result, not a failure.** The detector matches",
                "AI-infrastructure conventions — a `retrieval/`, `tools/`,",
                "`memory/` directory or a well-known dependency. A project with",
                "different naming, or one that is not AI infrastructure, produces",
                "nothing. Read the structure above and the source directly.",
                "",
            ]
        )
        return lines

    by_confidence: dict[Confidence, list[Candidate]] = {c: [] for c in Confidence}
    for candidate in report.candidates:
        by_confidence[candidate.confidence].append(candidate)

    for confidence in (Confidence.STRONG, Confidence.MODERATE, Confidence.WEAK):
        group = by_confidence[confidence]
        if not group:
            continue
        lines.extend(
            [
                f"### {confidence.value.upper()} ({len(group)})",
                "",
                f"*{CONFIDENCE_MEANING[confidence]}*",
                "",
            ]
        )
        for candidate in group:
            lines.append(f"#### {candidate.name} — `{candidate.pattern_id}`")
            lines.append("")
            lines.append(f"**Category:** `{candidate.category}`")
            lines.append("")
            lines.append(f"**Evidence** ({candidate.evidence_kind}):")
            lines.append("")
            lines.extend(_evidence_lines(candidate))
            lines.append("")
            lines.append(f"**Limitation:** {candidate.limitations}")
            lines.append("")

    return lines


def _render_classification(report: StudyReport) -> list[str]:
    lines = ["## Taxonomy mapping", ""]

    if not report.classifications:
        lines.extend(["Nothing to map.", ""])
        return lines

    mapped = [c for c in report.classifications if not c.proposes_new_category]
    proposed = [c for c in report.classifications if c.proposes_new_category]

    if mapped:
        lines.extend(
            [
                "### Already in the taxonomy",
                "",
                "These confirm that the taxonomy covers ground this project also",
                "found worth building. They are **not** adoption candidates on",
                "that basis alone.",
                "",
                "| Pattern | Taxonomy category |",
                "|---|---|",
            ]
        )
        for classification in mapped:
            category = classification.mapped_category
            name = category.name if category else classification.candidate.category
            lines.append(f"| `{classification.candidate.pattern_id}` | `{name}` |")
        lines.append("")

    if proposed:
        lines.extend(
            [
                "### Proposed new categories",
                "",
                "> These are **proposals for review**, not taxonomy changes. The",
                "> pipeline does not edit `TAXONOMY.md` (ADR-0021 Decision 2).",
                "> Adopting one is a session decision requiring an ADR, and the",
                "> proposed id is derived from the pattern so that two projects",
                "> reporting the same pattern propose the same id.",
                "",
                "| Proposed id | From pattern | Why it is new |",
                "|---|---|---|",
            ]
        )
        for classification in proposed:
            lines.append(
                f"| `{classification.proposed_id}` "
                f"| `{classification.candidate.pattern_id}` "
                f"| category `{classification.candidate.category}` is not in the "
                "taxonomy tree |"
            )
        lines.append("")
    else:
        lines.extend(["No new categories proposed.", ""])

    return lines


def _render_open_questions(report: StudyReport) -> list[str]:
    """Questions the next session must answer by reading the code.

    Generated from what the pipeline *could not* determine. This is the section
    that converts a structural report into a work item, and it is deliberately
    phrased as questions rather than conclusions.
    """
    lines = [
        "## Open questions for the next session",
        "",
        "The pipeline cannot answer these; each requires reading the source. They",
        "are what a session should resolve before proposing adoption.",
        "",
    ]
    questions: list[str] = []

    for candidate in report.candidates:
        if candidate.confidence is Confidence.WEAK:
            questions.append(
                f"- `{candidate.pattern_id}`: is `{candidate.evidence_paths[0]}` "
                "implemented machinery or a stub? The name alone cannot say."
            )

    if report.inventory.test_file_count == 0:
        questions.append(
            "- No test files were detected. Is the project tested elsewhere, or "
            "genuinely untested? This bears on how much its design can be trusted."
        )

    unparsed = [m for m in report.inventory.manifests if m.error]
    for manifest in unparsed:
        questions.append(f"- `{manifest.path}` could not be parsed ({manifest.error}).")

    if not questions:
        questions.append(
            "- Which of the STRONG candidates is load-bearing for this project, "
            "and which is incidental? Structure cannot distinguish them."
        )

    lines.extend(questions)
    lines.append("")
    return lines


def render_report(report: StudyReport) -> str:
    """Render the full Markdown report.

    Pure: takes a :class:`StudyReport` and returns text. Writing is the caller's
    job, which keeps the renderer testable without touching the filesystem and
    keeps every filesystem write in one place (`study_pipeline.reportwriter`).
    """
    sections = [
        _render_header(report),
        _render_provenance(report),
        _render_limitations(report),
        _render_structure(report),
        _render_dependencies(report),
        _render_findings(report),
        _render_classification(report),
        _render_open_questions(report),
    ]
    body = "\n".join(line for section in sections for line in section)
    # Collapse runs of blank lines so the output is stable and diffable.
    while "\n\n\n\n" in body:
        body = body.replace("\n\n\n\n", "\n\n\n")
    return body.rstrip("\n") + "\n"


def _today() -> str:
    """Today's date in UTC.

    Explicitly UTC rather than `date.today()`, which depends on the machine's
    timezone: a report is a dated artifact, and two runs of the same study on
    machines in different zones must not produce different dates for the same
    commit (ruff DTZ011).
    """
    return dt.datetime.now(dt.UTC).date().isoformat()


def build_report(
    *,
    slug: str,
    url: str,
    commit: str,
    size_bytes: int,
    inventory: Inventory,
    candidates: tuple[Candidate, ...],
    classifications: tuple[Classification, ...],
    taxonomy: Taxonomy,
    studied_on: str | None = None,
    incomplete_reason: str = "",
) -> StudyReport:
    """Assemble a :class:`StudyReport`.

    `studied_on` defaults to today. It is passed through rather than always
    computed so a test can assert exact output.
    """
    return StudyReport(
        slug=slug,
        url=url,
        commit=commit,
        studied_on=studied_on or _today(),
        size_bytes=size_bytes,
        inventory=inventory,
        candidates=candidates,
        classifications=classifications,
        taxonomy=taxonomy,
        incomplete_reason=incomplete_reason,
    )


def report_path(root: Path, report: StudyReport) -> Path:
    """Absolute path a report is written to."""
    return root / REPORTS_DIRNAME / report.filename
